project:
  type: website

website:
  title: "Simulation Accelerator 🚀"
  navbar:
     left:
      - text: "ℹ️ About"
        menu:
          - text: "What is the Simulation accelerator?"
            file: about/about.qmd
          - text: "Learner Personas"
            file: about/learner-personas.qmd
          - text: "Prerequisites"
            file: about/prerequisites.qmd
      - text: "📋 Practical Information"
        menu:
          - text: "📅 Schedule"
            file: practical_information/schedule.qmd
          - text: "💻 Set up"
            file: practical_information/set-up.qmd
          - text: "🧑‍🏫 Your tutors"
            file: practical_information/tutors.qmd
      - text: "📚 Learning Materials"
        menu:
          - text: "Overview"
            file: learning_materials/index.qmd
          - text: "✨ Map"
            file: learning_materials/1_reusable/index.qmd
          - text: "❔ Model"
            file: learning_materials/2_visible/index.qmd
          - text: "🎰 Random"
            file: learning_materials/3_collaborative/index.qmd
          - text: "👥 Valid"
            file: learning_materials/4_reliable/index.qmd
          - text: "🏆 Capstone"
            file: learning_materials/5_capstone/index.qmd
     right: 
        - icon: github
          href: https://github.com/The-Strategy-Unit/simulation-accelerator


      
  announcement:
    icon: exclamation-triangle-fill
    dismissable: true
    content: "Site in progress"
    type: secondary
    position: below-navbar

format:
  html:
    theme: brand
    css:
      - _SUBrand.StyleSheet.css
    toc: true



