---
format:
  html:
    toc: false
---

:::: {.card-row}

::: {.card-box}

## ℹ️ About Simulation Accelerator

Learn more about [how the accelerator programme works](about/about.qmd), see if this programme is [aimed at you](about/learner-personas.qmd), and check you meet [the prerequisites](about/prerequisites.qmd).
:::

::: {.card-box}
## 📋 Practical Information

 Once you're enrolled, you can find practical information including the [schedule](practical_information/schedule.qmd), getting your [laptop set-up](practical_information/set-up.qmd) and information about [your tutors](practical_information/tutors.qmd).
:::

::: {.card-box}
## 📚 Learning Materials

All our [learning materials](learning_materials/index.qmd) are available online to explore at your own pace. 

:::

::::

<style>
.card-row {
  display: flex;
  gap: 1rem;
  margin: 2rem 0;
}
.card-box {
  flex: 1;
  padding: 1.5rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  background-color: rgba(var(--bs-secondary-rgb), 0.08);
}

.card-box h2 {
  margin-top: 0;
}

</style>


Welcome to the Simulation Accelerator. A programme for ICB analysts starting their simulation journey, building the foundational skills to apply this approach in practice. This programme runs from January – March 2027 and is funded by the Strategic Commissioning Intelligence Centre (SCIC).