---
title: "Getting set up"
format:
  html:
    toc: false
---

Before the first session, install:

- Python [Install Python](https://www.python.org/downloads/)
- A code editor (choose one):
  - [VS Code](https://code.visualstudio.com/) — great for Python or R [Recommended]
  - [Positron](https://positron.posit.co/) — great for Python or R

## 📦 Packages

Ideally, you should have sufficient admin rights on your machine to install the packages that you need as and when you require them.
To start off with, here are some packages that we recommend for R and Python:

### Recommended Python packages

- [simpy](https://docs.astral.sh/simpy/getting-started/installation/#pypi) for simulation modeling
- [uv](https://docs.astral.sh/uv/getting-started/installation/#pypi) for package management 
- [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html) for data wrangling
- [ruff](https://docs.astral.sh/ruff/) for formatting and linting

## ☁️ Cloud environment

If you have issues using Python on your work computer do not worry, we will be working with [JupyterLite](https://jupyterlite.readthedocs.io/en/latest/) as a backup. JupyterLite is a free online environment where you can run Python code without installing anything. However, there are some limitations.

- Limited for later work on your own project
- Cloud based - you cannot upload sensitive data

You'll get much more from this programme if you're able to work on your own machine. JupyterLite is just a nice way for us to be able to introduce concepts and get you started thinking about simulation concepts without having to know too much Python. 



