---
title: "About the programme"
format:
  html:
    toc: true
---

## 📦 What is Simulation?

Simulation is an analytical technique used to model complex systems and processes in order to:

* understand behavior 
* identify the impact of potential improvements/interventions 
* make predictions about their performance under different scenarios

In healthcare, simulation can be used to model patient flow, resource allocation, and identify bottlenecks, among other things. Healthcare systems are complex and dynamic, with many interacting components, making it difficult to predict how changes will affect outcomes. Simulation provides a way to explore these complexities in a controlled environment.

Simulation involves creating a virtual representation of a real-world system that accurately mimics its behavior, allowing analysts to experiment with different scenarios and assess the potential impact of change.

## 🚀 What is the Simulation Accelerator?

A programme for ICB analysts starting their simulation journey, building the foundational skills to apply this approach in practice. Some coding experience is expected (see [prerequisites](prerequisites.qmd)), along with enthusiasm to learn.

It runs as a _flipped classroom_. You'll work through learning material at your own pace before each session, then use session time with tutors for discussion, problem-solving, and going deeper.

## 📖 Course outline

| Theme | Topics |
|---------|-------|--------|
| ♻️ [Reusable](../learning_materials/1_reusable/index.qmd) | Write modular, well-documented code that's easy for you and others to understand and reuse |
| 📖 [Visible](../learning_materials/2_visible/index.qmd) | Make your projects easy to find and use with clear READMEs, licences, and documentation |
| 👥 [Collaborative](../learning_materials/3_collaborative/index.qmd) | Work effectively with others using Git, code review, and good communication habits |
| 🛡️ [Reliable](../learning_materials/4_reliable/index.qmd) | Build trust in your code through testing, automation, and reproducible environments|
| 🏆 [Capstone](../learning_materials/5_capstone/index.qmd) | Put it all into practice on a real project with feedback and support |

Each session includes:

- 60-90 mins of self-directed pre-work (reading, small exercises)
- 60 mins contact session with the tutors

We'll also have an online community for attendees to ask questions to tutors or chat with peers running throughout the ten weeks.

We won't cover:

- Basic R or Python programming (We [expect you to already know a little programming](prerequisites.qmd))
- Plotting and visualisation
- Modelling and machine learning
- Using LLMs
- Building interactive web apps
