---
title: "🎰 Random"
subtitle: "Harness your data and run a stochastic simulation trial"
format:
  html:
    toc: true
---

## Overview

In this session you'll learn about stochasticity and why it's important in simulation to understand and capture uncertainty. We'll look at different types of uncertainty, where they come from and how to measure them when running a simulation trial. 

As part of this session we'll be fitting statistical distributions to our data and using them to drive our simulation model. We'll also look at setting the seed for random number generation to allow reproducibility of our results.

## 🎯 Learning objectives

By the end of this session, you should be able to:

- Fit simple statistical distributions to your data 
- Use fitted distributions to drive your simulation model
- Set the seed for random number generation
- Capture the uncertainty caused by stochasticity in your simulation results and understand how to interpret them

## 📖 Before the session

Please complete the [pre-learning materials](pre-learning.qmd). These typically take 60 – 90 minutes and are essential for getting the most out of the session.

## 🖥️ During the session

[View the slides →](slides.qmd)

